### ISSUE TITLE
docs: add notes about method naming

### ISSUE THREAD

**Issue by rodmax** [rodmax/react-playground#143]
Try to extract rationale part from https://www.yegor256.com/2018/08/22/builders-and-manipulators.html to `naming.md`
due to maintainer of this repo mostly followed it

...and may be search for another approaches

**Comment by harunou** [comment]
how to align 
```
interface Bookshelf {
   books(): Book[];
   setBooks(books: Book[]): void
}
```
to the article

**Comment by rodmax** [comment]
@harunou, the interface you suggested is good enough from point of my understanding of  the article

could you please point me what is confusing you? 

p.s.
i personally  have difficulties
when it comes to asynchronous queries like

```ts
books(): Promise<Book[]>
vs
loadBooks(): Promise<Book[]>
```

right now i use `loadBooks()` name but not sure if this is correct

**Comment by rodmax** [comment]
:thinking: i'm not sure about `saveFile()` but `getTitle()` should be renamed to `title()`

Article just says
- name *actions* as verb
- and *builders(query)* as noun

and article not comments how many camelCase worlds should be in the method name so `setBooks()` looks good if returned `void` 


i guess `saveFile()` return file descriptor or file object so author recommends name it `file()`



> In typed language i don't think prefix load is required for async queries

here i disagree, type system say you about promise, but it not say about `load or create locally`

**Comment by rodmax** [comment]
and even more [shorter](https://stackoverflow.com/a/1991341)

> One of the more universal, yet simple rules is: Function names should be verbs if the function changes the state of the program, and nouns if they're used to return a certain value.

**Comment by rodmax** [comment]
And the finally winner candidate https://swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage

It's may exceptions from Egor approach but looks promising
